### ISSUE TITLE
Ver si se puede reemplazar el while de generateList() por un map + lambda expression

### ISSUE THREAD

**Issue by juanbono** [dds-frd-utn/grupo7#1]
Capaz el while de generateList() se puede reemplazar por algo asi como 

``` java
ArrayList<Job> jobsList = new ArrayList<Job>();
jsonObject.map( job -> jobsList.add(createJob(job)) );
```

Despues me fijo cuando este en linux.

**Comment by sergioviera** [comment]
si usas java 8 si se puede!

2015-07-17 7:02 GMT-03:00 Juan Bono notifications@github.com:

**Comment by juanbono** [comment]
Sisi jaja
